 development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: htpp_test
  pool: 5
  username: abbeytipton
  password:
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: headachetracker
  username:
  password:
  host: postgres://ivspuvfmaybwzh:5db25dcec8c6cb4c5f9a280cec7e960d45ee17b2eca4fec9b37b72a6192b7597@ec2-184-73-216-48.compute-1.amazonaws.com:5432/d9tmom50paf9sd
  sslmode: require
